In [1]:
import numpy as np

In [2]:
ar1=np.array(27)

In [3]:
ar1

array(27)

In [4]:
type(ar1)

numpy.ndarray

In [9]:
ar2=np.array([[2,3,4],[1,0,1]])

In [10]:
ar2

array([[2, 3, 4],
       [1, 0, 1]])

array types;
1,zero array
2,ones array 
3,empty array 
4,array for range

In [15]:
zero_array=np.zeros([6,5])

In [16]:
zero_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
ar3=np.arange(2,9,2)

In [28]:
ar3

array([2, 4, 6, 8])

In [30]:
ar5=np.transpose(ar3)

In [31]:
ar5

array([2, 4, 6, 8])

In [32]:
ar6=np.transpose(ar5)

In [33]:
ar6

array([2, 4, 6, 8])

In [39]:
a1=np.array([1,2])
a2=np.array([4,5])

In [40]:
a1

array([1, 2])

In [43]:
concat=np.concatenate((a1,a2))

In [44]:
concat

array([1, 2, 4, 5])

In [46]:
hori=np.hstack((a1,a2))

In [47]:
hori

array([1, 2, 4, 5])