In [2]:
import numpy as np

In [2]:
ar1=np.array(27)

In [3]:
ar1

array(27)

In [4]:
type(ar1)

numpy.ndarray

In [9]:
ar2=np.array([[2,3,4],[1,0,1]])

In [10]:
ar2

array([[2, 3, 4],
       [1, 0, 1]])

array types;
1,zero array
2,ones array 
3,empty array 
4,array for range

In [15]:
zero_array=np.zeros([6,5])

In [16]:
zero_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
ar3=np.arange(2,9,2)

In [28]:
ar3

array([2, 4, 6, 8])

In [30]:
ar5=np.transpose(ar3)

In [31]:
ar5

array([2, 4, 6, 8])

In [32]:
ar6=np.transpose(ar5)

In [33]:
ar6

array([2, 4, 6, 8])

In [39]:
a1=np.array([1,2])
a2=np.array([4,5])

In [40]:
a1

array([1, 2])

In [43]:
concat=np.concatenate((a1,a2))

In [44]:
concat

array([1, 2, 4, 5])

In [46]:
hori=np.hstack((a1,a2))

In [47]:
hori

array([1, 2, 4, 5])

In [8]:
mat1=np.array([[1,2,3],[4,7,8],[2,5,6]])


In [9]:
mat1

array([[1, 2, 3],
       [4, 7, 8],
       [2, 5, 6]])

In [10]:
det_of_mat1=np.linalg.det(mat1)

In [11]:
det_of_mat1

3.999999999999999

In [12]:
inverse=np.linalg.inv(mat1)

In [13]:
inverse

array([[ 5.00000000e-01,  7.50000000e-01, -1.25000000e+00],
       [-2.00000000e+00,  1.48029737e-16,  1.00000000e+00],
       [ 1.50000000e+00, -2.50000000e-01, -2.50000000e-01]])

In [14]:
Dense=np.array([[1,0,0,0],[0,0,2,0],[1,2,0,0],[0,0,1,1]])

In [15]:
Dense

array([[1, 0, 0, 0],
       [0, 0, 2, 0],
       [1, 2, 0, 0],
       [0, 0, 1, 1]])

In [18]:
from scipy.sparse import csr_matrix

In [19]:
sparse=csr_matrix(Dense)

In [20]:
sparse

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 6 stored elements in Compressed Sparse Row format>

In [21]:
print(sparse)

  (0, 0)	1
  (1, 2)	2
  (2, 0)	1
  (2, 1)	2
  (3, 2)	1
  (3, 3)	1
